@rootUrl = http://localhost:8000/api/admin/v1  

### signuo
POST {{rootUrl}}/auth/signup
Content-Type: application/json

{
  "fName":   "test",
  "lName":   "test",
  "email":   "test@gmail.com",
  "password": "123"
}

### verify the email

GET {{rootUrl}}/auth/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzUyOTgwNzIwLCJleHAiOjE3NTI5ODE2MjB9.h5w3nnL0MpfIlTO4BCMBSbGov2qaeKhAhrcZQIPTAPs

### LOGIN

POST  {{rootUrl}}/auth/login
Content-Type: application/json

{
    "email" :"test@gmail.com",
    "password" : "123"
}

###create category

POST http://localhost:8000/api/admin/v1/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUyOTgxODU1LCJleHAiOjE3NTMwNjgyNTV9.8xaufY-fk2yPohnsg93HJuzhQohmyZ_yXG_JVFjMELM

{
  "name": "lectrooo"
}

###List all the categories
GET {{rootUrl}}/categories
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjcyOTgzMCwiZXhwIjoxNzUyODE2MjMwfQ.4DVczHis1rTEkF43ql7jOWk2gdiT00BpfEExO5GYShU

###delete the categories
DELETE {{rootUrl}}/categories/6876fd4751a0344d0fb9f068
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjcyOTgzMCwiZXhwIjoxNzUyODE2MjMwfQ.4DVczHis1rTEkF43ql7jOWk2gdiT00BpfEExO5GYShU


###create a product
POST {{rootUrl}}/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjczMTM3NSwiZXhwIjoxNzUyODE3Nzc1fQ.TQqXns5Zhy3-5QZXWoVTsvJHaGL-yH3SsjEgMTlQ7Wo

{
  "name": "ipad",
  "description": "laptop",
  "price": 29.99,
  "stock": 100,
  "category": "687888eeee54c11272fd9179",
  "images": ["https://upload.wikimedia.org/wikipedia/commons/b/b2/MOUSE.jpg"]
}

### List Products
GET http://localhost:8000/api/admin/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjczMTM3NSwiZXhwIjoxNzUyODE3Nzc1fQ.TQqXns5Zhy3-5QZXWoVTsvJHaGL-yH3SsjEgMTlQ7Wo

### Delete Product
DELETE http://localhost:8000/api/admin/v1/products/68788f298530dda4e6cfd6fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjczMTM3NSwiZXhwIjoxNzUyODE3Nzc1fQ.TQqXns5Zhy3-5QZXWoVTsvJHaGL-yH3SsjEgMTlQ7Wo


###check order
GET {{rootUrl}}/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MjczMzEzNSwiZXhwIjoxNzUyODE5NTM1fQ.TJuKYYDoLFEcWhmUGnDlzvHafAwZlfZu8aPjbJFIyYA


###test reviews
PUT {{rootUrl}}/reviews/68771a535c8cb4f53fb2a234/approve
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1Mjk3Mjk4NCwiZXhwIjoxNzUzMDU5Mzg0fQ.AEJy6kplJHsNucEI8N_x8FG6sVWQUu0X_HCCLERM_gw

###delete reviews
### Delete review
DELETE http://localhost:8000/api/admin/v1/reviews/68771a535c8cb4f53fb2a234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbm9qQGdhbWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1Mjk3MzM4NywiZXhwIjoxNzUzMDU5Nzg3fQ.9qKu4gMAW3FlUiDZpEh7S-wKPp9CbYd8hBCoyNa0mkc

###testing joi validation
post {{rootUrl}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUyOTgxOTE3LCJleHAiOjE3NTMwNjgzMTd9.tzwi_muDv6V94snsTRIX3zT4NdOO-ryoJLVjafqaJFo

{
  
  "price": 649,
  "stock": 25,
  "category": "64b08df18d0b9babc1234567",
  "images": []
}
